#!/bin/bash -e

declare -p EXIT_SUCCESS &> /dev/null || readonly EXIT_SUCCESS=0
declare -p EXIT_FAILURE &> /dev/null || readonly EXIT_FAILURE=1

echo "Installing requirements for project...";

if ! command -v sudo &> /dev/null;
then
    echo "'sudo' needle.";
    echo "Run 'apt install sudo' before install.";
    exit $EXIT_FAILURE;
fi;

if [ "$(basename "$(pwd)")" != 'data-relay' ]
then
    echo "Run from root project directory.";
    exit $EXIT_FAILURE;
fi;

sudo apt update;
sudo apt install --yes python3;
sudo apt install --yes python3-pip;
sudo apt install --yes python3-venv;

/usr/bin/python3 -m venv venv;
source venv/bin/activate;

venv/bin/pip3 install --upgrade pip;
venv/bin/pip3 install --upgrade build;
venv/bin/pip3 install --upgrade twine;

pip freeze > requirements.txt;
pip install --requirement requirements.txt;

echo "Requirements installed.";
